src/main/java/org/richardstallman/dvback/client/python/PythonService.java
src/main/java/org/richardstallman/dvback/client/python/PythonServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/question/converter/QuestionConverter.java
src/main/java/org/richardstallman/dvback/domain/question/domain/external/response/QuestionExternalResponseDto.java
src/main/java/org/richardstallman/dvback/domain/question/service/QuestionServiceImpl.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/static.docs/app.adoc

🌱 작업한 브랜치
DV-39-be-generate-questions
- 파이썬 연결 로직
- 코드리뷰 hasNext ? get~ 반영 (https://github.com/TeamRichardStallman/DV-Back/pull/4#discussion_r1818560884)
- 테스트 코드 간단 수정 사항 반영
.env 파일에 PYTHON_SERVER_URL 추가하고 danny가 최신이라고 알려준대로 파이썬이 작성되어 있어야 돌아갑니다.
https://www.notion.so/_Joy-12361cc3398380a78aabd25d9ef168a4?pvs=4
개발 과정 위 링크 참고해주세요! 파이썬 로컬에서 같이 돌아가게 바꿔봤는데 혹시 돌려보고 싶으시면 보내드리겠습니다
! 테스트 코드 없는 이유
제가 부족해서 연결 로직 테스트는 2시간 해봤는데 실패했습니다 ㅠㅠ postman으론 잘 동작해서 시간 없으니까 일단 보류하고 기능 구현 다 되고 프론트까지 작업하고 클린코드 / 예외처리 할 때 다시 도전해보겠습니다 ㅠㅠ

[DV-39] BE Generate Questions

---

src/main/java/org/richardstallman/dvback/client/s3/config/S3Config.java
src/main/java/org/richardstallman/dvback/client/s3/service/S3ServiceImpl.java

🌱 작업한 브랜치
- DV-81-be-s3-연결
- S3 연결 에러 해결
- URL 유효기간 설정 코드 수정

Dv 81 be s3 연결

---

src/docs/asciidoc/app.adoc
src/main/java/org/richardstallman/dvback/domain/user/controller/UserController.java
src/main/java/org/richardstallman/dvback/domain/user/service/UserServiceImpl.java
src/main/resources/static/docs/app.html
src/test/java/org/richardstallman/dvback/domain/user/controller/UserControllerTest.java

🌱 작업한 브랜치
- DV-118-회원-정보-조회
- 회원 정보 조회
https://www.notion.so/_-5cbd3e3e56f14417aff012947f16e6dd?pvs=4
-> postman 테스트 성공 사진
크게 작업한 게 없어서 빠르게 탈퇴 작업한 것도 마무리해서 올리겠습니다.

[DV-114] feat: 회원 정보 조회

---

src/main/java/org/richardstallman/dvback/common/constant/CommonConstants.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/AnswerEvaluationExternalDomain.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/OverallEvaluationExternalDomain.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/request/EvaluationExternalRequestDto.java
src/main/java/org/richardstallman/dvback/domain/evaluation/service/EvaluationServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/question/converter/QuestionConverter.java
src/main/java/org/richardstallman/dvback/domain/question/domain/QuestionDomain.java
src/main/java/org/richardstallman/dvback/domain/question/domain/external/QuestionExternalDomain.java
src/main/java/org/richardstallman/dvback/domain/question/domain/external/request/QuestionExternalRequestDto.java
src/main/java/org/richardstallman/dvback/domain/question/domain/request/QuestionInitialRequestDto.java
src/main/java/org/richardstallman/dvback/domain/question/entity/QuestionEntity.java
src/main/resources/static/docs/app.html
src/test/java/org/richardstallman/dvback/domain/question/controller/QuestionControllerTest.java

🌱 작업한 브랜치
- DV-122-be-ai-connections
- 전달값 맞춰서 수정

[DV-122-be-ai-connections] refactor : ai 전달값 맞춰서 수정

---

src/main/java/org/richardstallman/dvback/common/constant/CommonConstants.java
src/main/java/org/richardstallman/dvback/common/ping/controller/PingController.java
src/main/java/org/richardstallman/dvback/domain/file/converter/CoverLetterConverter.java
src/main/java/org/richardstallman/dvback/domain/file/entity/CoverLetterEntity.java
src/main/java/org/richardstallman/dvback/domain/interview/converter/InterviewConverter.java
src/main/java/org/richardstallman/dvback/domain/interview/service/InterviewServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/question/domain/external/request/QuestionExternalRequestDto.java

🌱 작업한 브랜치
DV-126-be-front-connections
- 프론트 요청사항 반영

refactor : 프론트 요청사항 반영

---

src/main/java/org/richardstallman/dvback/domain/answer/entity/AnswerEntity.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/request/EvaluationExternalAnswerRequestDto.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/request/EvaluationExternalAnswersRequestDto.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/request/EvaluationExternalQuestionRequestDto.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/request/EvaluationExternalQuestionsRequestDto.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/external/request/EvaluationExternalRequestDto.java
src/main/java/org/richardstallman/dvback/domain/evaluation/service/EvaluationServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/interview/converter/InterviewConverter.java
src/main/java/org/richardstallman/dvback/domain/question/controller/QuestionController.java
src/main/java/org/richardstallman/dvback/domain/question/converter/QuestionConverter.java
src/main/java/org/richardstallman/dvback/domain/question/domain/external/request/QuestionExternalRequestDto.java
src/main/java/org/richardstallman/dvback/domain/question/service/QuestionService.java
src/main/java/org/richardstallman/dvback/domain/question/service/QuestionServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/question/controller/QuestionControllerTest.java

🌱 작업한 브랜치
- DV-132-be-connection-complete
- 인공지능 - 백 테스트 완료

refactor : 프론트 / 백  /인공지능 연결 제대로 되도록

---

build.gradle
src/main/java/org/richardstallman/dvback/global/config/web/MvcConfig.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

🌱 작업한 브랜치
- DV-123-be-외부-logging-연결
- 코드가 서버에서 동작될 때 모니터링을 할 수 있도록 변경

Dv 123 be 외부 logging 연결

---

src/main/java/org/richardstallman/dvback/domain/user/controller/UserController.java
src/main/java/org/richardstallman/dvback/domain/user/service/UserService.java
src/main/java/org/richardstallman/dvback/domain/user/service/UserServiceImpl.java
src/main/java/org/richardstallman/dvback/global/oauth/service/CookieService.java
src/main/java/org/richardstallman/dvback/global/oauth/service/TokenService.java

🌱 작업한 브랜치
- DV-156-BE-로그아웃-오류 해결
- 로그아웃 시 토큰이 안 사라지는 문제가 있었는데 해당 부분을 해결했습니다.
- https://www.notion.so/_-a5adcd61ad2a4ba28e4863adfb654c5a?pvs=4
ㄴ 토큰 사라진 모습과 redis 사진 
- 일단 local끼리는 문제가 없는데 혹시 서버에서 문제 생기면 다시 해결하겠습니다.

Dv 156 be 로그아웃 오류 해결

---

src/main/java/org/richardstallman/dvback/domain/user/controller/UserController.java
src/test/java/org/richardstallman/dvback/domain/user/controller/UserControllerTest.java

🌱 작업한 브랜치
- DV-159-로그인-여부-확인
- 토큰을 기반으로 로그인이 되었는지 조회하는 엔드포인트를 작업했습니다.
- https://www.notion.so/_-4587905e0875430f8dd00fa45fe9e387?pvs=4
ㄴ 해당 엔드포인트 관련 포스트맨, 테스트 내역

DV-159  BE 로그인 여부 확인

---

Dockerfile
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

🌱 작업한 브랜치
- DV-123-be-외부-logging-연결
- Log 모니터링을 위한 셋팅입니다.

[DV-123] feat : Log Monitoring 추가

---

src/main/java/org/richardstallman/dvback/domain/comment/controller/CommentController.java
src/main/java/org/richardstallman/dvback/domain/comment/converter/CommentConverter.java
src/main/java/org/richardstallman/dvback/domain/comment/domain/CommentDomain.java
src/main/java/org/richardstallman/dvback/domain/comment/domain/request/CommentCreateRequestDto.java
src/main/java/org/richardstallman/dvback/domain/comment/domain/response/CommentDeleteResponseDto.java
src/main/java/org/richardstallman/dvback/domain/comment/domain/response/CommentListResponseDto.java
src/main/java/org/richardstallman/dvback/domain/comment/domain/response/CommentResponseDto.java
src/main/java/org/richardstallman/dvback/domain/comment/entity/CommentEntity.java
src/main/java/org/richardstallman/dvback/domain/comment/repository/CommentJpaRepository.java
src/main/java/org/richardstallman/dvback/domain/comment/repository/CommentRepository.java
src/main/java/org/richardstallman/dvback/domain/comment/repository/CommentRepositoryImpl.java
src/main/java/org/richardstallman/dvback/domain/comment/service/CommentService.java
src/main/java/org/richardstallman/dvback/domain/comment/service/CommentServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/post/repository/PostRepository.java
src/main/java/org/richardstallman/dvback/domain/post/repository/PostRepositoryImpl.java
src/main/java/org/richardstallman/dvback/domain/post/service/PostService.java
src/main/java/org/richardstallman/dvback/domain/post/service/PostServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/comment/controller/CommentControllerTest.java

🌱 작업한 브랜치
- DV-177-be-comment-implements
1. 댓글 추가
2. 댓글 삭제
3. 게시글 삭제 시 댓글 삭제(service만)
4. 게시글 조회 시 댓글 목록 조회
5. 내가 쓴 댓글 목록 조회
- 게시글 식별자로 게시글 조회 기능 추가
- spotless / build / 실행 / swagger 테스트 완료

Dv 177 be comment implements

---

src/main/java/org/richardstallman/dvback/client/s3/service/S3Service.java
src/main/java/org/richardstallman/dvback/client/s3/service/S3ServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/file/controller/FileController.java
src/main/java/org/richardstallman/dvback/domain/user/converter/UserConverter.java
src/main/java/org/richardstallman/dvback/domain/user/domain/UserDomain.java
src/main/java/org/richardstallman/dvback/domain/user/domain/request/UserRequestDto.java
src/main/java/org/richardstallman/dvback/domain/user/entity/UserEntity.java
src/main/java/org/richardstallman/dvback/domain/user/service/UserServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/file/controller/FileControllerTest.java
src/test/java/org/richardstallman/dvback/domain/user/controller/UserControllerTest.java

🌱 작업한 브랜치
- DV-178-be-프로필-이미지-관련-수정
- requst: objectkey / response: url
- https://www.notion.so/_-2223cde542494344a9c9fd6ad7161f60?pvs=4
ㄴ 관련해서 간단하게 적어둔 노션

Dv 178 be 프로필 이미지 관련 수정

---

src/main/java/org/richardstallman/dvback/client/firebase/config/FirebaseConfig.java
src/test/java/org/richardstallman/dvback/domain/evaluation/controller/EvaluationControllerTest.java

🌱 작업한 브랜치
- Dv-191-be-add-new-google-account-and-fcm-config
- 구글 계정 변경 및 테스트코드 수정
- .env 추가사항 따로 공유 예정

feat : 구글 계정 변경 및 평가 테스트 코드 보완

---

src/main/java/org/richardstallman/dvback/domain/user/controller/UserController.java
src/main/java/org/richardstallman/dvback/domain/user/converter/UserConverter.java
src/main/java/org/richardstallman/dvback/domain/user/domain/request/UserUpdateRequestDto.java
src/main/java/org/richardstallman/dvback/domain/user/service/UserService.java
src/main/java/org/richardstallman/dvback/domain/user/service/UserServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/user/controller/UserControllerTest.java

🌱 작업한 브랜치
- DV-195-be-회원-정보-수정-기능-구현
- 마이페이지 회원 정보 수정시 필요한 endpoint 구현

Dv 195 be 회원 정보 수정 기능 구현

---

src/main/java/org/richardstallman/dvback/domain/answer/converter/AnswerConverter.java
src/main/java/org/richardstallman/dvback/domain/evaluation/domain/overall/request/OverallEvaluationResultRequestDto.java
src/main/java/org/richardstallman/dvback/domain/question/domain/external/request/QuestionExternalSttRequestDto.java
src/main/java/org/richardstallman/dvback/domain/question/service/QuestionServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/evaluation/controller/EvaluationControllerTest.java

🌱 작업한 브랜치
- DV-203-be-update-payload
- 인공지능 요청에 맞게 페이로드 변경
- 빌드 / spotless / 실행 테스트 완

feat : 인공지능 요청으로 payload에 맞게 변경

---

src/main/java/org/richardstallman/dvback/client/s3/service/S3ServiceImpl.java

🌱 작업한 브랜치
- Dv-207-s3-경로-변경
- s3 경로 변경
- 빌드, 스타일 모두 확인
- 일단 이미지를 보고 작성했는데 혹시 잘못됐거나 놓친 부분이 있다면 알려주세요.

fix : s3 경로 변경

---

src/main/java/org/richardstallman/dvback/client/s3/service/S3Service.java
src/main/java/org/richardstallman/dvback/client/s3/service/S3ServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/file/controller/FileController.java
src/test/java/org/richardstallman/dvback/domain/answer/controller/AnswerControllerTest.java
src/test/java/org/richardstallman/dvback/domain/file/controller/FileControllerTest.java

🌱 작업한 브랜치
- DV-208-be-audio-presignedurl-implement
- 오디오 업로드 presignedurl 작업
- 오디오 다운로드 presignedurl 작업
- 빌드, 스타일 적용 완료

[DV-208] feat: 오디오 presignedurl 관련 작업

---

src/main/java/org/richardstallman/dvback/domain/user/service/UserServiceImpl.java

🌱 작업한 브랜치
- DV-221-be---회원-정보-길이-제한
- username, nickname, name 길이 제한
- 빌드, 스타일 적용 완료

[DV-221] feat: 회원 정보 길이 제한

---

src/main/java/org/richardstallman/dvback/domain/post/converter/PostConverter.java
src/main/java/org/richardstallman/dvback/domain/post/domain/response/PostCreateResponseDto.java
src/main/java/org/richardstallman/dvback/domain/post/service/PostServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/post/controller/PostControllerTest.java

🌱 작업한 브랜치
- DV-228-be-sns-update
- 게시글 정보 반환 시 작성자 정보 반환
- authorId, authorNickname, authorProfileUrl
- spotless, build, 실행 완료

DV-228-be-sns-update

---

src/main/java/org/richardstallman/dvback/domain/interview/controller/InterviewController.java
src/main/java/org/richardstallman/dvback/domain/interview/service/InterviewService.java
src/main/java/org/richardstallman/dvback/domain/interview/service/InterviewServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/interview/controller/InterviewControllerTest.java

🌱 작업한 브랜치
- DV-226-be---본인-확인-엔드포인트-구현
- 해당 인터뷰의 소유자가 맞는지
- 평가가 완료된 인터뷰가 아닌지 확인
- 빌드, 스타일, swagger 테스트 완료

[DV-226] feat: 본인 확인 엔드포인트 구현

---

src/main/java/org/richardstallman/dvback/domain/answer/service/AnswerServiceImpl.java
src/main/java/org/richardstallman/dvback/domain/file/controller/FileController.java
src/main/java/org/richardstallman/dvback/domain/file/converter/CoverLetterConverter.java
src/main/java/org/richardstallman/dvback/domain/file/service/CoverLetterService.java
src/main/java/org/richardstallman/dvback/domain/file/service/CoverLetterServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/file/controller/FileControllerTest.java

🌱 작업한 브랜치
- DV-234-be-update-voice-and-s3-logic
- 마이페이지에서 파일 업로드 endpoint 추가
- build, spotless, 실행 완료

Dv 234 be update voice and s3 logic

---

src/main/java/org/richardstallman/dvback/client/s3/service/S3Service.java
src/main/java/org/richardstallman/dvback/client/s3/service/S3ServiceImpl.java
src/main/java/org/richardstallman/dvback/common/constant/CommonConstants.java
src/main/java/org/richardstallman/dvback/domain/evaluation/entity/answer/AnswerEvaluationScoreEntity.java
src/main/java/org/richardstallman/dvback/domain/file/controller/FileController.java
src/main/java/org/richardstallman/dvback/domain/post/controller/PostController.java
src/main/java/org/richardstallman/dvback/domain/post/converter/PostConverter.java
src/main/java/org/richardstallman/dvback/domain/post/domain/request/PostAddImageRequestDto.java
src/main/java/org/richardstallman/dvback/domain/post/service/PostService.java
src/main/java/org/richardstallman/dvback/domain/post/service/PostServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/file/controller/FileControllerTest.java
src/test/java/org/richardstallman/dvback/domain/post/controller/PostControllerTest.java

🌱 작업한 브랜치
- DV-255-be-update-refund-and-sns
- sns 이미지 업로드 기능 추가
- build, 실행, spotless apply 완료

DV-255-be-update-refund-and-sns

---

src/main/java/org/richardstallman/dvback/domain/post/repository/PostJpaRepository.java
src/main/java/org/richardstallman/dvback/domain/post/repository/PostRepositoryImpl.java
src/main/java/org/richardstallman/dvback/domain/subscription/controller/SubscriptionController.java
src/main/java/org/richardstallman/dvback/domain/subscription/repostiroy/SubscriptionJpaRepository.java
src/main/java/org/richardstallman/dvback/domain/subscription/repostiroy/SubscriptionRepository.java
src/main/java/org/richardstallman/dvback/domain/subscription/repostiroy/SubscriptionRepositoryImpl.java
src/main/java/org/richardstallman/dvback/domain/subscription/service/SubscriptionServiceImpl.java
src/test/java/org/richardstallman/dvback/domain/subscription/controller/SubscriptionControllerTest.java

🌱 작업한 브랜치
- DV-259-be-update-subscription-and-post-order
- 구독 취소 직무 식별자 / 유저 식별자 기준으로 변경
- 피드 시간 역순으로 조회
- spotless / build / 실행 완료

DV-259-be-update-subscription-and-post-order

---

src/main/resources/application-prod.yml

💬 관련 이슈
- 배포 서버 음성 안됨
- S3 service에서 s3 bucket 이름을 properties에서참조하는데 dev 설정을 변경

hotfix: S3 bucket이름 dev로 고정 해제 및 개발 서버 jpa ddl 수정
